### PR TITLE
Add original key information on new API if available

### PR DESCRIPTION
**Pull request by chrisroberts**
This addresses issue #21. It is an alternative approach to #22 that does
not require the addition of new attributes to support the implementation
specifics around the STS setup.

### CODE REVIEW

**Comment by chrisroberts** [comment]
I'm not super happy with this implementation, mainly due to lack of easily accessible override points for the API implementation details. Ideally this can be refactored shortly to be isolated into a specific 'after setup' override and remove the requirement of additional readers.

**Comment by imbriaco** [comment]
I would like to suggest that accessing `data` in the way that this PR does is pretty similar to the approach that #22 takes since it's effectively fiddling with internal functionality, but in a way that may be somewhat less obviously intention revealing. 

Could you explain why you like this approach better? I'd like to try to better match my style to what you're looking for when I submit future PRs.

Thanks!

**Comment by imbriaco** [comment]
The more I think about this, the trickier it becomes. We can't know for sure if it's appropriate to use the original credentials or whether we should be using the assumed role and that it will be able to further assume additional roles with the way that we're currently storing the original credentials.

It seems to me that we need to store a map of the role ARN along with the original credentials. I _think_  can probably infer that if we are assuming a role that we've previously assumed, we probably should use the credentials we used last time, at least within the scope of the object's lifetime. If that's the case, we could store a map of role_arn and creds that were used to assume it. I'll take a swing at this and link the commit here so you can see what I mean.

**Comment by chrisroberts** [comment]
Hi! So the current state of this PR should be a little bit clearer. I've got the stub setup and now making use of it to persist customized credential information. As I was typing up a previous reply to you, I noticed that one of my assumptions was incorrect, and applied some updates make my assumption correct. To go back to your previous comment:

Storing the extra information within `data` as opposed to being a defined `attribute` on the API implementation has little to do with hiding intention, but I can see how the implementation can be confusing. The idea with the `attribute` declarations is that they are the interface for me as a user to interact with the API (what credentials and information are required to use this API). This intention is why I'm hesitant to include attribute declarations for data that is only required by the underlying implementation. 

What I was going to say next was that by passing through the token information (and the new + original keys) allows us to just build the instance directly without having to make another request to the STS service and retrieve new keys + token. However, this was completely not the case as it would just automatically hit the STS service if the role was defined. So, that's been properly updated _and_ an update has been added to do expiration checks which I hadn't implemented yet.

Having the stub to override makes things a bit more clear on how information is being persisted and makes things a bit cleaner which is a happy side effect. 

Now, onto this last comment, I believe what you are referencing is when the fetched STS token/credentials expire and need to be renewed. The originals will always be the _original_ user credentials, not the fetched credentials from the STS service. This allows for renewing the credentials from the STS service after expiry even if we have moved to a new API connection. If you were referencing something else (assuming multiple roles or (?)) can you provide a little more context.

Thanks!

**Comment by imbriaco** [comment]
Thanks for the detailed write-up, that's incredibly helpful. Knowing that the attributes are intended to represent the public interface makes things much clearer. Totally agreed that's not a good place to cache the original credentials now that i know that. 

That should have been more obvious to me, but I've had a relatively difficult time working through all of the class hierarchy and module inclusion to get a full picture of how things hang together. It's starting to become clear, but there's quite a lot going on.

I see the expiry on the credentials now, good stuff! I hadn't even noticed it was missing. My primary use case has been SparkleFormation (thanks, by the way) and my scripts have all completed before the generated tokens expired, so I never ran into it. :)

The final issue is indeed multiple roles. Imagine a user has permission to assume Role A, but not Role B. Role A, in turn, has the ability to assume Role B. If we always used the original credentials, we couldn't support the case where User -> assumes Role A -> assumes Role B since we'd revert to the base credentials for the attempt to assume Role B. Make sense?

I'm thinking we may want to basically store the equivalent of `originals[creds[:aws_sts_role_arn]]` and only reuse the originals when we see that the STS attempt is to assume the same role? If you have assumed a new role, we should use those role credentials for _everything_ except for trying to assume the same role again. Maybe I'm overthinking it, though.

**Comment by chrisroberts** [comment]
There's not a ton of documentation around the miasma libraries yet. I've been working from the outside in starting with the sparkleformation stuff, so hopefully that will be getting better soon. Thanks for taking the time to work through it :)

So, at first when I read that final paragraph I was like:

whaaat

But I think it finally clicked and I get what you're attempting to do. So, multiple assume roles, with each iteration of the assume using the previously provided credentials. This is cool, and not something I had considered. I don't think we need to retain the credentials as we assume new roles since the only time we will need the originals is if we expire. At that point, they will likely all end up expiring, in which case we can just roll back to the start, and assume role until we get to the target. Would having the ability to provide an array of roles to assume which can be iterated over to reach the final role provide the correct functionality? I'm pretty sure the implementation there will be pretty straight forward.

Now, from the the question (in my mind) moves to: What if I have different roles for different services?

That one will be harder (but not impossible) implementation wise.

**Comment by imbriaco** [comment]
You got it, that case where you go through a sequence of roles is what I was trying to describe.

So this is the point where I shrug and say "I dunno!" because I don't use roles that way either, it just occurred to me as I was working through that code that the way it was written was unlikely to work for that case.  

I sort of hate the idea of iterating over roles and trying them until one works. Maybe the right answer is just to leave it as an exercise to the reader to create a new client instance if they need to jump from one assumed role to another one. They can prime the new instance with the temporary credentials from the intermediate one that they assumed.

This has the advantage of not requiring more work in the library. ;)

**Comment by chrisroberts** [comment]
Ah, okay then! Yes, I like easier. I've still been toying around with allowing API specific roles (so you can have a different role assumed for CFN than is assumed for EC2) but I'll likely sit on an implementation until someone has a solid requirement for it :smiley:

**Comment by chrisroberts** [comment]
ship it!

**Pull request merged**
