### PR TITLE
Fix the time check for role update and use explicit host override attribute

### PR DESCRIPTION
**Pull request by chrisroberts**

### CODE REVIEW

**Comment by chrisroberts** [comment]
merge

**Comment by imbriaco** [comment]
I was just about to open a PR for this. Thanks for catching it. :+1:

**Comment by cixelsyd** [comment]
Woo-hoo!  Thanks, Chris, you rock!

**Comment by chrisroberts** [comment]
@cixelsyd you bet! sorry about falling off IRC suddenly but thanks for pinging me!

**Pull request merged**
